use jwt_simple::prelude::Serialize;
use serde_json::Value;

use crate::api::master_all::get_masters;
use crate::api::{ApiRequest, NotificationData, RemoteData};
use crate::call::{CallCustom, CallResponse};
use crate::master;

#[derive(Default, Debug, Serialize)]
pub struct GachaInfo {
  pub gacha: Vec<GachaItem>,
}

impl CallCustom for GachaInfo {}

#[derive(Debug, Clone, Serialize)]
pub struct GachaItem {
  pub gachaid: u32,
  #[serde(with = "crate::bool_as_int")]
  pub daily: bool,
  pub type1: String,
  pub val1: u32,
  pub type10: String,
  pub val10: u32,
  pub ticket: u32,
  pub ticket_num: u32,
  pub draw_count: u32,
  pub remain_draw_count: u32,
  pub upperlimitcount: u32,
  pub user_story_id: u32,
  pub stepup_bonus: Option<StepupBonus>,
  pub random_bonus: Option<RandomBonus>,
  pub stepup_info: Option<StepupInfo>,
  pub select_info: Option<SelectInfo>,
  pub continuation_info: Option<ContinuationInfo>,
  pub member_select_info: Option<MemberSelectInfo>,
  pub first_free_ids: Vec<u32>,
}

#[derive(Debug, Clone, Serialize)]
// Unknown structure
pub struct StepupBonus;

#[derive(Debug, Clone, Serialize)]
pub struct RandomBonus {
  pub gacha_item_id: u32,
  pub items: Vec<RandomBonusItem>,
}

#[derive(Debug, Clone, Serialize)]
pub struct RandomBonusItem {
  pub pack_id: u32,
  pub rate: u32,
}

#[derive(Debug, Clone, Serialize)]
pub struct StepupInfo {
  pub step: u32,
  #[serde(rename = "loop")]
  pub loop_count: u32,
  pub is_drawable: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct SelectInfo {
  pub select_character_id: u32,
  pub select_character_id_list: Vec<u32>,
}

#[derive(Debug, Clone, Serialize)]
// Unknown structure
pub struct ContinuationInfo;

#[derive(Debug, Clone, Serialize)]
pub struct MemberSelectInfo {
  pub select_member_id_list: Vec<u32>,
}

impl GachaItem {
  pub fn new_simple(gachaid: u32) -> Self {
    Self {
      gachaid,
      daily: true,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 1,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    }
  }
}

#[derive(Debug, Serialize)]
pub struct GachaTutorial {
  pub gacha_id: u32,
  pub goods: Vec<GachaGoodItem>,
}

impl CallCustom for GachaTutorial {}

#[derive(Debug, Serialize)]
pub struct GachaGoodItem {
  pub item_type: u8,
  pub item_id: u32,
  pub item_num: u32,
  #[serde(with = "crate::bool_as_int")]
  pub is_new: bool,
}

impl GachaGoodItem {
  pub fn new(item_type: u8, item_id: u32, item_num: u32, is_new: bool) -> Self {
    Self {
      item_type,
      item_id,
      item_num,
      is_new,
    }
  }
}

#[derive(Default, Debug, Serialize)]
pub struct GachaResult {
  pub gacha_id: u32,
  pub goods: Vec<GachaGood>,
  pub bonus_info: BonusInfo,
  pub bonus_step: Option<()>,
}

impl CallCustom for GachaResult {}

#[derive(Default, Debug, Serialize)]
pub struct GachaGood {
  pub itemtype: u8,
  pub itemid: u32,
  pub itemnum: u32,
  #[serde(with = "crate::bool_as_int")]
  pub isnew: bool,
}

impl GachaGood {
  pub fn new(itemtype: u8, itemid: u32, itemnum: u32, isnew: bool) -> Self {
    Self {
      itemtype,
      itemid,
      itemnum,
      isnew,
    }
  }
}

#[derive(Default, Debug, Serialize)]
pub struct BonusInfo {
  pub items: Vec<BonusItem>,
  pub rare: u32,
  pub bonus_type: u32,
  pub bonus_animation: String,
}

#[derive(Default, Debug, Serialize)]
pub struct BonusItem {
  pub item_type: u32,
  pub item_id: u32,
  pub item_num: u32,
}

pub async fn gacha_info(_request: ApiRequest) -> anyhow::Result<(CallResponse<dyn CallCustom>, bool)> {
  let gacha_items = vec![
    GachaItem {
      gachaid: 100001,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 6,
      ticket_num: 10,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410321,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 24,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 323083,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 8,
      ticket_num: 30,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 200021,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 17,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 323083,
      daily: true,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 1,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410211,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 19,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 500007,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 1,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410248,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 20,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410305,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 21,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410317,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 23,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410321,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 24,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410326,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 25,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410353,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 26,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410364,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 27,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410393,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 28,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410395,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 29,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: Some(RandomBonus {
        gacha_item_id: 41039501,
        items: vec![
          RandomBonusItem {
            pack_id: 241039501,
            rate: 100,
          },
          RandomBonusItem {
            pack_id: 241039502,
            rate: 1000,
          },
          RandomBonusItem {
            pack_id: 241039503,
            rate: 5000,
          },
          RandomBonusItem {
            pack_id: 241039504,
            rate: 7900,
          },
          RandomBonusItem {
            pack_id: 241039505,
            rate: 8000,
          },
          RandomBonusItem {
            pack_id: 241039506,
            rate: 10000,
          },
          RandomBonusItem {
            pack_id: 241039507,
            rate: 10000,
          },
          RandomBonusItem {
            pack_id: 241039508,
            rate: 10000,
          },
          RandomBonusItem {
            pack_id: 241039509,
            rate: 16000,
          },
          RandomBonusItem {
            pack_id: 241039510,
            rate: 16000,
          },
          RandomBonusItem {
            pack_id: 241039511,
            rate: 16000,
          },
        ],
      }),
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410402,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 30,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410403,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 31,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410410,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 32,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410430,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 33,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410433,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 1,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: Some(MemberSelectInfo {
        select_member_id_list: vec![],
      }),
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410436,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 1,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: Some(SelectInfo {
        select_character_id: 0,
        select_character_id_list: vec![
          100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 108, 151, 128,
          169,
        ],
      }),
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410437,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 34,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410441,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 35,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410458,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 36,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410486,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 37,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410490,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 38,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410509,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 39,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410522,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 40,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410531,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 41,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410535,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: "limit".to_string(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 5,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410536,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 1,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410544,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 42,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410546,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 43,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410548,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 44,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410550,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 45,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410552,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 46,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410553,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: "limit".to_string(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 3,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410554,
      daily: false,
      type1: "step".to_string(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 0,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: Some(StepupInfo {
        step: 0,
        loop_count: 0,
        is_drawable: true,
      }),
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410627,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 53,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410639,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 54,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410653,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 56,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410661,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 57,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
    GachaItem {
      gachaid: 410670,
      daily: false,
      type1: String::new(),
      val1: 0,
      type10: String::new(),
      val10: 0,
      ticket: 58,
      ticket_num: 0,
      draw_count: 0,
      remain_draw_count: 0,
      upperlimitcount: 0,
      user_story_id: 0,
      stepup_bonus: None,
      random_bonus: None,
      stepup_info: None,
      select_info: None,
      continuation_info: None,
      member_select_info: None,
      first_free_ids: vec![],
    },
  ];

  let master = &get_masters().await["gacha"].master_decompressed;
  let master: Vec<master::gacha::Gacha> = serde_json::from_str(master).unwrap();
  let mut response: CallResponse<dyn CallCustom> = CallResponse::new_success(Box::new(GachaInfo {
    gacha: master
      .iter()
      // .filter(|gacha| gacha.gacha_id != "323083")
      .map(|gacha| GachaItem::new_simple(gacha.gacha_id.parse().unwrap()))
      .collect(),
    // gacha: vec![
    //   // GachaItem::new_simple(323083),
    //   GachaItem {
    //     gachaid: 410436,
    //     daily: false,
    //     type1: String::new(),
    //     val1: 0,
    //     type10: String::new(),
    //     val10: 0,
    //     ticket: 0,
    //     ticket_num: 0,
    //     draw_count: 0,
    //     remain_draw_count: 1,
    //     upperlimitcount: 0,
    //     user_story_id: 0,
    //     stepup_bonus: None,
    //     random_bonus: None,
    //     stepup_info: None,
    //     select_info: Some(SelectInfo {
    //       select_character_id: 0,
    //       select_character_id_list: vec![
    //         100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 108, 151,
    //         128, 169,
    //       ],
    //     }),
    //     continuation_info: None,
    //     member_select_info: None,
    //     first_free_ids: vec![],
    //   },
    //   GachaItem {
    //     gachaid: 323041,
    //     daily: false,
    //     type1: String::new(),
    //     val1: 0,
    //     type10: String::new(),
    //     val10: 0,
    //     ticket: 0,
    //     ticket_num: 0,
    //     draw_count: 0,
    //     remain_draw_count: 1,
    //     upperlimitcount: 0,
    //     user_story_id: 0,
    //     stepup_bonus: None,
    //     random_bonus: None,
    //     stepup_info: None,
    //     select_info: None,
    //     continuation_info: None,
    //     member_select_info: None,
    //     first_free_ids: vec![],
    //   },
    // ],
    // gacha: gacha_items,
  }));
  // response.time = Some(1723059410); // 7 Aug 2024
  // response.time = Some(1722718800); // 4 Aug 2024
  #[rustfmt::skip]
  response.add_notifications(vec![
    // also present 100001 and 500007
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 200012, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410535, msgkey: String::new(), tag: String::new(), },
    NotificationData { cmd: 1, kind: 12, key: 19, value: 323041, msgkey: String::new(), tag: String::new(), }, // missing
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410553, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410123, msgkey: String::new(), tag: String::new(), },
    NotificationData { cmd: 1, kind: 12, key: 19, value: 410436, msgkey: String::new(), tag: String::new(), }, // present
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410565, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410433, msgkey: String::new(), tag: String::new(), }, // present
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410564, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410554, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410554, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410554, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410554, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 12, key: 19, value: 410554, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 26, key: 200012, value: 1, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 26, key: 323083, value: 1, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 26, key: 410436, value: 1, msgkey: String::new(), tag: String::new(), }, // present ref
    NotificationData { cmd: 1, kind: 26, key: 323041, value: 1, msgkey: String::new(), tag: String::new(), }, // missing ref
    // NotificationData { cmd: 1, kind: 26, key: 410554, value: 1, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 27, key: 410535, value: 0, msgkey: String::new(), tag: String::new(), },
    // NotificationData { cmd: 1, kind: 27, key: 410554, value: 0, msgkey: String::new(), tag: String::new(), },
  ]);
  Ok((response, false))
}

pub async fn gacha_tutorial(request: ApiRequest) -> anyhow::Result<(CallResponse<dyn CallCustom>, bool)> {
  if request.body["type"] == "1" {
    Ok((
      CallResponse::new_success(Box::new(GachaTutorial {
        gacha_id: 100002,
        goods: vec![
          GachaGoodItem::new(4, 1032102, 1, true),
          GachaGoodItem::new(4, 1692100, 1, true),
          GachaGoodItem::new(4, 1182100, 1, true),
          GachaGoodItem::new(4, 1092100, 1, true),
          GachaGoodItem::new(4, 1024126, 1, true),
          GachaGoodItem::new(4, 1092100, 1, true),
          GachaGoodItem::new(4, 1002100, 1, true),
          GachaGoodItem::new(4, 1052102, 1, true),
          GachaGoodItem::new(4, 1083100, 1, true),
          GachaGoodItem::new(4, 1174130, 1, true),
        ],
      })),
      false,
    ))
  } else {
    Ok((
      CallResponse::new_success(Box::new(GachaTutorial {
        gacha_id: 100002,
        goods: vec![],
      })),
      false,
    ))
  }
}

pub async fn gacha_tutorial_reward(_request: ApiRequest) -> anyhow::Result<(CallResponse<dyn CallCustom>, bool)> {
  let response = include_str!("../gacha-tutorial-reward.json");
  let response: Value = serde_json::from_str(response).unwrap();
  Ok((CallResponse::new_success(Box::new(response)), false))
}

pub async fn gacha_chain(request: ApiRequest) -> anyhow::Result<(CallResponse<dyn CallCustom>, bool)> {
  let gacha_id: u32 = request.body["gacha_id"].parse().unwrap();
  let _money_type: u8 = request.body["money_type"].parse().unwrap();

  let mut response: CallResponse<dyn CallCustom> = CallResponse::new_success(Box::new(GachaResult {
    gacha_id,
    goods: vec![
      GachaGood::new(4, 1032102, 1, true),
      GachaGood::new(4, 1012100, 1, true),
      GachaGood::new(4, 1013100, 1, true),
      GachaGood::new(4, 1012100, 1, true),
      GachaGood::new(4, 1013116, 1, true),
      GachaGood::new(4, 1012102, 1, true),
      GachaGood::new(4, 1012102, 1, true),
      GachaGood::new(4, 1012102, 1, true),
      GachaGood::new(4, 1012100, 1, true),
      GachaGood::new(4, 1012102, 1, true),
      GachaGood::new(4, 1013116, 1, true),
    ],
    bonus_info: BonusInfo {
      items: vec![BonusItem {
        item_type: 49,
        item_id: 4,
        item_num: 1,
      }],
      rare: 0,
      bonus_type: 1,
      bonus_animation: "".to_owned(),
    },
    bonus_step: None,
  }));
  response.add_remote_data(vec![
    RemoteData::new(1, 7, 2, 11, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 3, 3, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 13, 7, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 34, 2, 0, 0, "show_button".to_string()),
    RemoteData::new(1, 6, 1, 30030001, 0, 0, "".to_string()),
    RemoteData::new(1, 10, 230731, 52307325, 0, 0, "".to_string()),
    RemoteData::new(1, 10, 230831, 52308305, 0, 0, "".to_string()),
  ]);

  Ok((response, false))
}

pub async fn gacha_normal(request: ApiRequest) -> anyhow::Result<(CallResponse<dyn CallCustom>, bool)> {
  let gacha_id: u32 = request.body["gacha_id"].parse().unwrap();
  let _money_type: u8 = request.body["money_type"].parse().unwrap();

  let mut response: CallResponse<dyn CallCustom> = CallResponse::new_success(Box::new(GachaResult {
    gacha_id,
    goods: vec![
      GachaGood::new(4, 1104100, 1, true),
      GachaGood::new(4, 1023104, 1, true), // 3*
      GachaGood::new(4, 1814100, 1, true),
      GachaGood::new(4, 1024225, 1, true),
      GachaGood::new(4, 1024118, 1, true),
      GachaGood::new(4, 1044200, 1, true),
      // GachaGood::new(4, 1193151, 1, true), // 3*
      // GachaGood::new(4, 1512100, 1, true), // 2*
      // GachaGood::new(4, 1081100, 1, true), // 1*
    ],
    bonus_info: BonusInfo {
      items: vec![BonusItem {
        item_type: 49,
        item_id: 4,
        item_num: 1,
      }],
      rare: 0,
      bonus_type: 1,
      bonus_animation: "".to_owned(),
    },
    bonus_step: None,
  }));
  response.add_remote_data(vec![
    RemoteData::new(1, 7, 2, 11, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 14, 1, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 3, 3, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 13, 7, 0, 0, "".to_string()),
    RemoteData::new(1, 7, 34, 2, 0, 0, "show_button".to_string()),
    RemoteData::new(1, 6, 1, 30030001, 0, 0, "".to_string()),
    RemoteData::new(1, 10, 230731, 52307325, 0, 0, "".to_string()),
    RemoteData::new(1, 10, 230831, 52308305, 0, 0, "".to_string()),
  ]);

  Ok((response, false))
}
