[package]
name = "axel-rsa-patcher"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
memmem = "0.1.1"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
